baseURL = 'https://thatmlopsguy.github.io/'
languageCode = 'en-us'
title = 'That MLOps Guy'
theme = "cactus2"
copyright = "That MLOps Guy"
enableRobotsTXT = false

[author]
name = "That MLOps Guy"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[menu]
[[menu.main]]
name = "ğŸ  Home"
url = "/"
weight = 1

[[menu.main]]
name = "âœï¸ Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "ğŸ“ Notes"
url = "/notes"
weight = 3

[[menu.main]]
name = "ğŸ‘¨â€ğŸ’» Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "ğŸ‘‹ About"
url = "/about"
weight = 5

[[menu.main]]
name = "âœ‰ï¸ Contact"
url = "/contact"
weight = 6

[[menu.main]]
name = "ğŸš€ Hire me"
url = "/hire"
weight = 7

[[menu.main]]
name = "ğŸ“Š Consulting"
url = "/consulting"
weight = 8

[[menu.main]]
name = "ğŸ’» Uses"
url = "/uses"
weight = 9

[[menu.main]]
name = "ğŸ“® Colophon"
url = "/colophon"
weight = 10

[[menu.main]]
name = "â• More"
url = "/more"
weight = 11

[params]
  colortheme = "dark" # dark, light, white, or classic
  mainSection = "posts"
  tagsOverview = false
  rss = true
  showReadTime = true
  sourceCodeUrl = "https://github.com/thatmlopsguy/thatmlopsguy.github.io"
  description = "Hi there! ğŸ‘‹ğŸ» I'm that MLOps guy. Cloud Architect, DevOps and Platform Engineer with more than 10 years of experience building and operating scalable platforms"
  about = """
  This is the place where I share my thoughts and notes about things that Iâ€™m excited about and
  working on and hope to connect with people having a similar mindset. 
  
  Iâ€™d love to hear from you!
  """
  showProjectsList = true
  projectsUrl = "https://github.com/thatmlopsguy"
  show_updated = true

[[params.social]]
  name = "github"
  link = "https://github.com/thatmlopsguy"

[languages]
  [languages.en.params]
    title = "MLOps Guy"
    subtitle = "A simple blog"
